db:
  url: "jdbc:mysql://localhost:3306/schmolify"
  username: "root"
  password: "mypassword"

jooq:
  sql:
    dialect: "MYSQL"
#
#db.url=jdbc:mysql://localhost:3306/schmolify
#db.username=root
#db.password=mypassword
#jooq.sql.dialect=MYSQL
